### ISSUE TITLE
Find a more natural way to check if a review exists with the given id

### ISSUE THREAD

**Issue by chrzrdx** [VenkatPantham/edyst-internship#3]
https://github.com/VenkatPantham/edyst-internship/blob/66c69f94e913473adcb2ec1cf07e6f8acb41cbcd/app.py#L300

Instead of querying the db twice with the review id, can you find a way to do so by querying it just the once?

**Comment by chrzrdx** [comment]
You can clean up your code in other places with this approach as well.

**Comment by VenkatPantham** [comment]
Changed the way to check for an item and modified the same to all.
